"""
Seed the ML baseline with synthetic normal-behaviour events and train the
Isolation Forest model.

Grounded in LANL 2015, CERT Insider Threat v6.2, and OTRF/Mordor datasets
(50 users × 9 profile types → ~8,000–12,000 events).

Run from the project root:
    python scripts/seed_baseline.py

No server needed — writes directly to forensic.db.
"""

import sys
from pathlib import Path

# Allow imports from the project root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.db.models import BaselineEventModel, Base, engine, SessionLocal, init_db
from backend.analysis import ml_synthetic as ml_synth
from backend.analysis import ml_anomaly

# ── host prefixes/names generated by ml_synthetic so we can replace them on re-run ──
_SYNTHETIC_HOST_PREFIXES = ("WORKSTATION-", "DB-SERVER-", "DEV-WS-", "EXEC-WS-")
_SYNTHETIC_HOST_EXACT = {
    "DC-01", "DC-02", "FILE-SERVER-01", "FILE-SERVER-02",
    "WEB-SERVER-01", "APP-SERVER-01", "PRINT-SERVER-01",
    "MGMT-SERVER-01", "BUILD-SERVER-01", "DEV-SERVER-01",
    "DB-SERVER-03", "BACKUP-01",
}


def _is_synthetic(host: str) -> bool:
    return (
        any(host.startswith(p) for p in _SYNTHETIC_HOST_PREFIXES)
        or host in _SYNTHETIC_HOST_EXACT
    )


def main() -> None:
    init_db()

    print("Generating synthetic baseline events …")
    events = ml_synth.generate_baseline_events(days=30)
    print(f"  {len(events):,} events across {len({e.user for e in events if e.user})} users")

    db = SessionLocal()
    try:
        # Remove any previously seeded synthetic rows (idempotent)
        existing = db.query(BaselineEventModel).all()
        stale_ids = [r.id for r in existing if _is_synthetic(r.source_host)]
        if stale_ids:
            db.query(BaselineEventModel).filter(
                BaselineEventModel.id.in_(stale_ids)
            ).delete(synchronize_session=False)
            db.commit()
            print(f"  Removed {len(stale_ids):,} stale synthetic rows")

        # Bulk-insert new baseline events
        rows = [
            BaselineEventModel(
                timestamp=e.timestamp,
                event_type=e.event_type,
                source_host=e.source_host,
                user=e.user,
                description=e.description,
                raw_source=e.raw_source.value,
                event_id=e.event_id,
            )
            for e in events
        ]
        db.bulk_save_objects(rows)
        db.commit()
        print(f"  Stored {len(rows):,} baseline events in forensic.db")

        # Train the Isolation Forest on baseline events only
        print("\nTraining Isolation Forest …")
        stats = ml_anomaly.train(events)
        print(
            f"  Model trained on {stats['trained_on_users']} users, "
            f"{stats['trained_on_events']:,} events"
        )
        print(f"  Saved to {ml_anomaly.MODEL_PATH}")

    finally:
        db.close()

    print("\nDone. The web app will now use this model for anomaly scoring.")
    print("To retrain with investigation data: POST /api/ml/train via the UI.")


if __name__ == "__main__":
    main()
