"""
Detection-as-Code — Sigma & Snort Rule Generator

Converts extracted MITRE techniques and IOCs into machine-readable detection
rules that the SOC team can import into SIEM/IDS platforms.

generate_behavioral_sigma_rules() additionally analyses the raw event timeline
and emits Sigma rules only when a behavioral sequence is actually present in
the data (evidence-gated). Patterns detected:
  1. Brute-force then success  (T1110)
  2. Encoded command execution (T1059.001)
  3. Lateral movement chain    (T1021)
  4. Recon then lateral move   (T1087 + T1021)
"""

import uuid
from collections import defaultdict
from datetime import timedelta
from backend.schema import ForensicEvent, IOC, MitreTechnique, RCAResult

# Starting SID for custom Snort rules (IANA private range 9000000+)
_SNORT_SID_BASE = 9_100_000

# Map MITRE tactic slugs to Sigma attack tag format
_TACTIC_TAG = {
    "Initial Access":        "initial_access",
    "Execution":             "execution",
    "Persistence":           "persistence",
    "Privilege Escalation":  "privilege_escalation",
    "Defense Evasion":       "defense_evasion",
    "Credential Access":     "credential_access",
    "Discovery":             "discovery",
    "Lateral Movement":      "lateral_movement",
    "Collection":            "collection",
    "Command and Control":   "command_and_control",
    "Exfiltration":          "exfiltration",
    "Impact":                "impact",
}

# Map MITRE tactic slugs to appropriate Sigma logsource
_LOGSOURCE_MAP: dict[str, dict] = {
    "execution":           {"product": "windows", "service": "sysmon"},
    "lateral_movement":    {"product": "windows", "service": "security"},
    "credential_access":   {"product": "windows", "service": "security"},
    "persistence":         {"product": "windows", "service": "security"},
    "defense_evasion":     {"product": "windows", "service": "sysmon"},
    "discovery":           {"product": "windows", "service": "security"},
    "command_and_control": {"category": "network_connection"},
}
_DEFAULT_LOGSOURCE: dict = {"product": "windows", "service": "security"}


def generate_sigma_rules(
    iocs: list[IOC],
    techniques: list[MitreTechnique],
) -> list[dict]:
    """
    Return a list of Sigma rule dicts (one per unique MITRE technique).
    Each dict is directly YAML-serialisable.
    """
    rules: list[dict] = []
    seen_ids: set[str] = set()

    for tech in techniques:
        if tech.id in seen_ids:
            continue
        seen_ids.add(tech.id)

        tactic_slug = _TACTIC_TAG.get(tech.tactic, tech.tactic.lower().replace(" ", "_"))
        # Use UUID5 so the same technique always produces the same rule ID
        rule_id = str(uuid.uuid5(uuid.NAMESPACE_OID, f"lateralx-{tech.id}"))

        # Pull the evidence keyword from the technique or fall back to the technique name
        keyword = (tech.evidence or tech.name).split("|")[0].strip()[:80]

        logsource = _LOGSOURCE_MAP.get(tactic_slug, _DEFAULT_LOGSOURCE)

        rule: dict = {
            "title": f"LateralX Detection — {tech.name}",
            "id": rule_id,
            "status": "experimental",
            "description": (
                f"Auto-generated by LateralX. "
                f"Technique {tech.id} ({tech.name}) detected in uploaded timeline."
            ),
            "references": [f"https://attack.mitre.org/techniques/{tech.id.replace('.', '/')}/"],
            "author": "LateralX",
            "logsource": logsource,
            "detection": {
                "keywords": [keyword],
                "condition": "keywords",
            },
            "falsepositives": ["Legitimate administrative activity"],
            "level": "high",
            "tags": [
                f"attack.{tactic_slug}",
                f"attack.{tech.id.lower()}",
            ],
        }
        rules.append(rule)

    return rules


def generate_snort_rules(iocs: list[IOC]) -> list[str]:
    """
    Return a list of Snort/Suricata rule strings, one per unique IP IOC.
    SIDs start at 9_100_000 to avoid conflict with community rule sets.
    """
    rules: list[str] = []
    seen: set[str] = set()

    for idx, ioc in enumerate(iocs):
        if ioc.type != "ip" or ioc.value in seen:
            continue
        seen.add(ioc.value)
        sid = _SNORT_SID_BASE + idx
        # Sanitise context: remove quotes that would break the Snort msg field
        msg = ioc.context.replace('"', "'")[:120]
        rule = (
            f'alert ip any any -> {ioc.value} any '
            f'(msg:"LateralX IOC — {msg}"; '
            f'sid:{sid}; rev:1;)'
        )
        rules.append(rule)

    return rules


_RECON_TOOLS = frozenset({
    "whoami", "net.exe", "net1.exe", "nltest", "tasklist", "ipconfig",
    "netstat", "arp", "nslookup", "ping", "systeminfo",
})

_LOGON_SUCCESS_IDS = frozenset({"4624", "4648", "4768", "4769"})
_LOGON_FAIL_ID = "4625"
_PROC_CREATE_ID = "4688"


def _sigma_rule(
    title: str,
    rule_key: str,
    description: str,
    keywords: list[str],
    condition: str,
    tags: list[str],
    level: str = "high",
) -> dict:
    rule_id = str(uuid.uuid5(uuid.NAMESPACE_OID, f"lateralx-behavioral-{rule_key}"))
    return {
        "title": title,
        "id": rule_id,
        "status": "experimental",
        "description": description,
        "references": [],
        "author": "LateralX",
        "logsource": {"product": "windows", "service": "security"},
        "detection": {"keywords": keywords, "condition": condition},
        "falsepositives": ["Authorized penetration testing", "Help-desk password resets"],
        "level": level,
        "tags": tags,
        "_source": "behavioral",
    }


def generate_behavioral_sigma_rules(events: list[ForensicEvent]) -> list[dict]:
    """
    Scan the event timeline for behavioral attack sequences and return Sigma
    rules only for patterns that have evidence in the supplied events.
    """
    rules: list[dict] = []

    # Index events by user
    by_user: dict[str, list[ForensicEvent]] = defaultdict(list)
    for e in events:
        if e.user:
            by_user[e.user].append(e)
    for evs in by_user.values():
        evs.sort(key=lambda e: e.timestamp)

    # ── Pattern 1: Brute-force then success ───────────────────────────────────
    # ≥3 failed logins within 10 min, followed by success within 5 min after.
    _bf_window = timedelta(minutes=10)
    _bf_success_lag = timedelta(minutes=5)
    bf_users: list[str] = []

    for user, evs in by_user.items():
        failures = [e for e in evs if e.event_id == _LOGON_FAIL_ID]
        successes = [e for e in evs if e.event_id in _LOGON_SUCCESS_IDS]
        for i in range(len(failures)):
            window_end = failures[i].timestamp + _bf_window
            burst = [f for f in failures[i:] if f.timestamp <= window_end]
            if len(burst) >= 3:
                cutoff = burst[-1].timestamp + _bf_success_lag
                if any(s.timestamp >= failures[i].timestamp and s.timestamp <= cutoff
                       for s in successes):
                    bf_users.append(user)
                    break

    if bf_users:
        rules.append(_sigma_rule(
            title="LateralX Behavioral — Brute-Force Authentication Followed by Success",
            rule_key="brute_force_success",
            description=(
                f"3+ consecutive failed logon attempts (EventID 4625) within 10 minutes "
                f"followed by a successful logon (EventID 4624/4648) within 5 minutes. "
                f"Evidence found for user(s): {', '.join(bf_users[:5])}."
            ),
            keywords=["EventID: 4625", "EventID: 4624", "EventID: 4648"],
            condition=(
                "selection_failure | count() by SubjectUserName > 3 within 10m | "
                "near selection_success within 5m"
            ),
            tags=["attack.credential_access", "attack.t1110"],
            level="high",
        ))

    # ── Pattern 2: Obfuscated / encoded command execution ─────────────────────
    _enc_markers = ("-enc", "encodedcommand", "base64")
    enc_events = [
        e for e in events
        if (e.event_id == _PROC_CREATE_ID or "process" in e.event_type.lower())
        and any(m in e.description.lower() for m in _enc_markers)
    ]

    if enc_events:
        hosts = list({e.source_host for e in enc_events})[:3]
        rules.append(_sigma_rule(
            title="LateralX Behavioral — Encoded PowerShell / Obfuscated Command Execution",
            rule_key="encoded_command_exec",
            description=(
                f"Process creation event (EventID 4688) with -EncodedCommand, "
                f"encodedcommand, or base64 in the command line detected on: "
                f"{', '.join(hosts)}."
            ),
            keywords=["-EncodedCommand", "EncodedCommand", "base64"],
            condition="keywords",
            tags=["attack.execution", "attack.t1059.001", "attack.defense_evasion", "attack.t1027"],
            level="high",
        ))

    # ── Pattern 3: Lateral movement chain ────────────────────────────────────
    # A user authenticates to ≥3 distinct hosts within 30 min.
    _lat_window = timedelta(minutes=30)
    lat_users: list[str] = []

    for user, evs in by_user.items():
        logons = [e for e in evs if e.event_id in _LOGON_SUCCESS_IDS
                  or "logon" in e.event_type.lower()]
        for i in range(len(logons)):
            win_end = logons[i].timestamp + _lat_window
            hosts_in_window = {e.source_host for e in logons
                               if logons[i].timestamp <= e.timestamp <= win_end}
            if len(hosts_in_window) >= 3:
                lat_users.append(user)
                break

    if lat_users:
        rules.append(_sigma_rule(
            title="LateralX Behavioral — Lateral Movement: Rapid Multi-Host Authentication",
            rule_key="lateral_movement_chain",
            description=(
                f"A single user authenticated to 3 or more distinct hosts within a "
                f"30-minute window, consistent with lateral movement. "
                f"Evidence found for user(s): {', '.join(lat_users[:5])}."
            ),
            keywords=["EventID: 4624", "EventID: 4648"],
            condition=(
                "selection | count(ComputerName) by SubjectUserName >= 3 within 30m"
            ),
            tags=["attack.lateral_movement", "attack.t1021"],
            level="high",
        ))

    # ── Pattern 4: Recon tools followed by lateral move ──────────────────────
    _recon_lag = timedelta(minutes=15)
    recon_pivot_users: list[str] = []

    for user, evs in by_user.items():
        recon_evs = [
            e for e in evs
            if any(t in e.description.lower() for t in _RECON_TOOLS)
        ]
        logon_evs = [e for e in evs if e.event_id in _LOGON_SUCCESS_IDS]
        for recon in recon_evs:
            cutoff = recon.timestamp + _recon_lag
            pivot = [
                l for l in logon_evs
                if l.timestamp > recon.timestamp
                and l.timestamp <= cutoff
                and l.source_host != recon.source_host
            ]
            if pivot:
                recon_pivot_users.append(user)
                break

    if recon_pivot_users:
        rules.append(_sigma_rule(
            title="LateralX Behavioral — Reconnaissance Followed by Lateral Movement",
            rule_key="recon_then_pivot",
            description=(
                f"Discovery/recon tool usage (whoami, net.exe, nltest, etc.) followed "
                f"within 15 minutes by a successful logon to a different host. "
                f"Evidence found for user(s): {', '.join(recon_pivot_users[:5])}."
            ),
            keywords=list(_RECON_TOOLS)[:6] + ["EventID: 4624"],
            condition=(
                "selection_recon | near selection_logon within 15m"
            ),
            tags=["attack.discovery", "attack.t1087", "attack.lateral_movement", "attack.t1021"],
            level="medium",
        ))

    # ── Pattern 5: Ransomware recovery-destruction triad (RANSOM-001) ──────────
    _RANSOM_KEYWORDS = ("vssadmin", "bcdedit", "wbadmin")
    ransom_hosts: list[str] = []
    proc_evs_ransom = [
        e for e in events
        if e.event_id in (_PROC_CREATE_ID, "1") and e.description
    ]
    host_ransom: dict[str, set[str]] = defaultdict(set)
    for e in proc_evs_ransom:
        dl = e.description.lower()
        for kw in _RANSOM_KEYWORDS:
            if kw in dl:
                host_ransom[e.source_host].add(kw)
    for host, found in host_ransom.items():
        if len(found) >= 2:
            ransom_hosts.append(host)

    if ransom_hosts:
        rules.append(_sigma_rule(
            title="LateralX Behavioral — Ransomware Recovery Destruction Triad",
            rule_key="ransomware_recovery_triad",
            description=(
                f"vssadmin Delete Shadows, bcdedit /set recoveryenabled No, and/or "
                f"wbadmin DELETE detected together — ransomware pre-encryption "
                f"recovery inhibition (T1490). Evidence on: {', '.join(ransom_hosts[:5])}."
            ),
            keywords=["vssadmin Delete Shadows", "bcdedit recoveryenabled", "wbadmin DELETE"],
            condition=(
                "selection_vss | near selection_bcd within 10m "
                "| near selection_wba within 10m"
            ),
            tags=["attack.impact", "attack.t1490"],
            level="high",
        ))

    # ── Pattern 6: NTLM brute-force by username (AUTH-001) ─────────────────────
    _ntlm_fail_evs = [e for e in events if e.event_id == "4776" and e.user]
    ntlm_by_user: dict[str, int] = defaultdict(int)
    for e in _ntlm_fail_evs:
        if any(code in (e.description or "").lower() for code in ("0xc000006", "error code")):
            ntlm_by_user[e.user] += 1
    brute_users = [u for u, cnt in ntlm_by_user.items() if cnt >= 20]

    if brute_users:
        rules.append(_sigma_rule(
            title="LateralX Behavioral — NTLM Brute-Force by Username",
            rule_key="ntlm_brute_force_user",
            description=(
                f"≥20 EID 4776 NTLM authentication failures for the same user account, "
                f"consistent with RDP/SMB password spraying (T1110.003). "
                f"Target account(s): {', '.join(brute_users[:5])}."
            ),
            keywords=["EventID: 4776", "0xC000006A", "0xC000006D"],
            condition=(
                "selection | count() by TargetUserName >= 20 within 30m"
            ),
            tags=["attack.credential_access", "attack.t1110.003"],
            level="high",
        ))

    # ── Pattern 7: Pass-the-Hash NTLM lateral logon (AUTH-002) ─────────────────
    pth_users: list[str] = []
    kerberos_users_set = {e.user for e in events if e.event_id == "4768" and e.user}
    ntlm_lateral_users: dict[str, int] = defaultdict(int)
    for e in events:
        if e.event_id in ("4624", "4648") and e.user and not e.user.endswith("$"):
            desc = (e.description or "").lower()
            if "ntlm" in desc and any(
                lt in desc for lt in ("logon type: 3", "type 3", "logon type: 9", "type 9")
            ):
                ntlm_lateral_users[e.user] += 1
    for user, count in ntlm_lateral_users.items():
        if user not in kerberos_users_set and count >= 2:
            pth_users.append(user)

    if pth_users:
        rules.append(_sigma_rule(
            title="LateralX Behavioral — Pass-the-Hash: NTLM Lateral Movement Without Kerberos",
            rule_key="pass_the_hash",
            description=(
                f"User performed ≥2 NTLM network logons (Type 3/9) with no Kerberos TGT "
                f"request in the session — NTLM-only lateral movement consistent with "
                f"Pass-the-Hash (T1550.002). Account(s): {', '.join(pth_users[:5])}."
            ),
            keywords=["EventID: 4624", "Authentication Package: NTLM", "Logon Type: 3"],
            condition=(
                "selection | where AuthenticationPackageName = 'NTLM' "
                "| where LogonType in (3, 9) | count() by SubjectUserName >= 2 "
                "| not near EventID_4768 within session"
            ),
            tags=["attack.lateral_movement", "attack.t1550.002", "attack.credential_access"],
            level="high",
        ))

    # ── Pattern 8: WMI shell spawn (LAT-001) ───────────────────────────────────
    wmi_spawn_hosts: list[str] = []
    for e in events:
        if (e.event_id == "1" and e.extra
                and "wmiprvse" in (e.extra.get("ParentImage") or "").lower()
                and any(sh in (e.extra.get("Image") or "").lower()
                        for sh in ("cmd.exe", "powershell.exe", "wscript.exe"))):
            wmi_spawn_hosts.append(e.source_host)

    if wmi_spawn_hosts:
        rules.append(_sigma_rule(
            title="LateralX Behavioral — WMI Lateral Execution: Shell Spawned by wmiprvse",
            rule_key="wmi_shell_spawn",
            description=(
                f"wmiprvse.exe (WMI provider host) spawned a command shell — definitive "
                f"indicator of WMI-based lateral execution (T1047). "
                f"Host(s): {', '.join(sorted(set(wmi_spawn_hosts))[:5])}."
            ),
            keywords=["wmiprvse.exe", "cmd.exe", "powershell.exe", "ParentImage"],
            condition=(
                "selection | where ParentImage endswith 'wmiprvse.exe' "
                "| where Image endswith ('cmd.exe', 'powershell.exe', 'wscript.exe')"
            ),
            tags=["attack.lateral_movement", "attack.t1047", "attack.execution"],
            level="high",
        ))

    # ── Pattern 9: Event log clearing sweep (EVADE-001) ────────────────────────
    log_clear_evs = [
        e for e in events
        if e.event_id == "1102"
        or (e.event_id in (_PROC_CREATE_ID, "1")
            and "wevtutil" in (e.description or "").lower()
            and "cl" in (e.description or "").lower())
    ]
    log_clear_hosts = list({e.source_host for e in log_clear_evs})

    if len(log_clear_hosts) >= 2:
        rules.append(_sigma_rule(
            title="LateralX Behavioral — Event Log Clearing Sweep Across Multiple Hosts",
            rule_key="log_clearing_sweep",
            description=(
                f"Event log cleared (EID 1102) or wevtutil cl executed on "
                f"{len(log_clear_hosts)} hosts — attacker anti-forensic sweep (T1070.001). "
                f"Hosts: {', '.join(sorted(log_clear_hosts)[:6])}."
            ),
            keywords=["EventID: 1102", "wevtutil cl Security", "wevtutil cl System"],
            condition="selection_1102 | count(Computer) >= 2",
            tags=["attack.defense_evasion", "attack.t1070.001"],
            level="high",
        ))
    elif log_clear_evs:
        rules.append(_sigma_rule(
            title="LateralX Behavioral — Event Log Cleared",
            rule_key="log_clearing_single",
            description=(
                f"Audit log cleared (EID 1102) or wevtutil cl detected on "
                f"{log_clear_hosts[0] if log_clear_hosts else 'unknown'} — T1070.001."
            ),
            keywords=["EventID: 1102", "wevtutil cl"],
            condition="selection_1102",
            tags=["attack.defense_evasion", "attack.t1070.001"],
            level="medium",
        ))

    return rules


# Behavioral YARA patterns keyed by MITRE technique ID.
# Each entry emits one named YARA rule when that technique appears in the result.
_YARA_TECH_PATTERNS: dict[str, tuple[str, str, list[str]]] = {
    # (rule_name, description, string_literals)
    "T1003.001": (
        "LateralX_LSASS_Credential_Dump",
        "LSASS memory access — credential dumping (T1003.001)",
        ['"lsass.exe"', '"SeDebugPrivilege"', '"MiniDumpWriteDump"', '"sekurlsa"'],
    ),
    "T1003.006": (
        "LateralX_DCSync_Replication",
        "DCSync via DRSUAPI replication call (T1003.006)",
        ['"drsuapi"', '"DsGetNCChanges"', '"DS-Replication-Get-Changes"', '"IDL_DRSGetNCChanges"'],
    ),
    "T1558.003": (
        "LateralX_Kerberoasting_TGS",
        "Kerberoasting — RC4 TGS ticket requests (T1558.003)",
        ['"$krb5tgs$"', '"RC4-HMAC"', '"etype 23"', '"kerberoast"'],
    ),
    "T1021.002": (
        "LateralX_SMB_Lateral_Movement",
        "SMB lateral movement via admin shares (T1021.002)",
        [r'"\\ADMIN$"', r'"\\IPC$"', r'"\\C$"', '"net use"'],
    ),
    "T1059.001": (
        "LateralX_Encoded_PowerShell",
        "Obfuscated / encoded PowerShell execution (T1059.001)",
        ['"-EncodedCommand"', '"encodedcommand" nocase', '"-enc " nocase', '"Invoke-Expression"'],
    ),
    "T1047": (
        "LateralX_WMI_Execution",
        "WMI lateral execution via Win32_Process (T1047)",
        ['"wmiexec"', '"Win32_Process"', '"WMI"', '"GetObject"'],
    ),
    "T1070.001": (
        "LateralX_EventLog_Clearing",
        "Windows event log clearing (T1070.001)",
        ['"wevtutil cl"', '"Clear-EventLog"', '"Clear-WinEvent"', '"wevtutil" nocase'],
    ),
    "T1055": (
        "LateralX_Process_Injection",
        "Process injection API sequence (T1055)",
        ['"VirtualAllocEx"', '"WriteProcessMemory"', '"CreateRemoteThread"', '"NtCreateThreadEx"'],
    ),
    "T1548": (
        "LateralX_Token_Privilege_Escalation",
        "Token privilege escalation (T1548)",
        ['"SeImpersonatePrivilege"', '"SeTcbPrivilege"', '"AdjustTokenPrivileges"', '"ImpersonateLoggedOnUser"'],
    ),
    "T1041": (
        "LateralX_Exfiltration_Channel",
        "Data exfiltration over C2 channel (T1041)",
        ['"Content-Length:"', '"POST /"', '"User-Agent:"', '"application/octet-stream"'],
    ),
    "T1490": (
        "LateralX_Inhibit_System_Recovery",
        "Ransomware recovery destruction — vssadmin/bcdedit/wbadmin triad (T1490)",
        ['"vssadmin"', '"Delete Shadows"', '"bcdedit"', '"recoveryenabled No"', '"wbadmin"'],
    ),
    "T1486": (
        "LateralX_Data_Encrypted_For_Impact",
        "Data encryption for impact — ransomware file encryption (T1486)",
        ['"CryptEncrypt"', '"EncryptFile"', '".BLACKVAULT"', '".locked"', '"ransom"'],
    ),
    "T1110.003": (
        "LateralX_Password_Spraying_RDP",
        "RDP/NTLM password spraying — repeated auth failures (T1110.003)",
        ['"0xC000006A"', '"0xC000006D"', '"NTLM"', '"Status: 0xC000006"'],
    ),
    "T1550.002": (
        "LateralX_Pass_The_Hash",
        "Pass-the-Hash NTLM lateral movement without Kerberos (T1550.002)",
        ['"Authentication Package: NTLM"', '"Logon Type: 3"', '"sekurlsa::pth"', '"pth"'],
    ),
}


def generate_yara_rules(
    iocs: list[IOC],
    techniques: list[MitreTechnique],
) -> list[str]:
    """
    Return YARA rule strings.

    Two categories:
    - Hash rules: one rule per unique MD5/SHA256 IOC, matching by file hash.
    - Behavioral rules: one rule per detected MITRE technique ID that has a
      known behavioral string-match pattern in _YARA_TECH_PATTERNS.
    """
    rules: list[str] = []

    # ── Hash-based file rules ─────────────────────────────────────────────────
    hashes: dict[str, list[str]] = {"md5": [], "sha256": []}
    for ioc in iocs:
        if ioc.type == "md5":
            hashes["md5"].append(ioc.value)
        elif ioc.type == "sha256":
            hashes["sha256"].append(ioc.value)

    if hashes["md5"] or hashes["sha256"]:
        cond_parts: list[str] = []
        if hashes["md5"]:
            md5_list = ", ".join(f'"{h}"' for h in hashes["md5"][:20])
            cond_parts.append(f"hash.md5(0, filesize) in ({md5_list})")
        if hashes["sha256"]:
            sha_list = ", ".join(f'"{h}"' for h in hashes["sha256"][:20])
            cond_parts.append(f"hash.sha256(0, filesize) in ({sha_list})")
        condition = " or\n        ".join(cond_parts)
        rules.append(
            f'import "hash"\n\n'
            f"rule LateralX_IOC_File_Hash\n{{\n"
            f"    meta:\n"
            f'        description = "File hash IOC match — extracted from LateralX incident analysis"\n'
            f'        author      = "LateralX Auto-Generator"\n'
            f'        severity    = "high"\n'
            f"    condition:\n"
            f"        {condition}\n"
            f"}}"
        )

    # ── Behavioral technique rules ────────────────────────────────────────────
    seen_techs: set[str] = set()
    for tech in techniques:
        tech_id = tech.id
        # Also check parent technique (e.g. T1003 for T1003.001)
        candidates = {tech_id, tech_id.split(".")[0]}
        for tid in candidates:
            if tid in seen_techs or tid not in _YARA_TECH_PATTERNS:
                continue
            seen_techs.add(tid)
            rule_name, description, strings = _YARA_TECH_PATTERNS[tid]
            str_defs = "\n".join(
                f"        $s{i} = {s}" for i, s in enumerate(strings)
            )
            str_cond = " or ".join(f"$s{i}" for i in range(len(strings)))
            rules.append(
                f"rule {rule_name}\n{{\n"
                f"    meta:\n"
                f'        description = "{description}"\n'
                f'        author      = "LateralX Auto-Generator"\n'
                f'        mitre_id    = "{tid}"\n'
                f'        severity    = "high"\n'
                f"    strings:\n"
                f"{str_defs}\n"
                f"    condition:\n"
                f"        {str_cond}\n"
                f"}}"
            )

    return rules


def generate_firewall_rules(iocs: list[IOC]) -> list[str]:
    """
    Return firewall blocking rules in three formats for each malicious IP IOC:
      - iptables (Linux)
      - Windows Firewall (netsh advfirewall)
      - Cisco ACL (extended access-list deny)
    One group of three rules per unique external IP.
    """
    rules: list[str] = []
    seen: set[str] = set()
    _RFC1918 = ("10.", "192.168.", "172.16.", "172.17.", "172.18.", "172.19.",
                "172.20.", "172.21.", "172.22.", "172.23.", "172.24.", "172.25.",
                "172.26.", "172.27.", "172.28.", "172.29.", "172.30.", "172.31.")

    for ioc in iocs:
        if ioc.type not in ("ip", "ip_address", "src_ip", "dst_ip"):
            continue
        ip = ioc.value.strip()
        if not ip or ip in seen:
            continue
        if any(ip.startswith(pfx) for pfx in _RFC1918):
            continue
        seen.add(ip)
        ctx = (ioc.context or "")[:60]
        rules.append(f"# Block {ip} — {ctx}")
        rules.append(f"iptables -I INPUT -s {ip} -j DROP && iptables -I OUTPUT -d {ip} -j DROP")
        rules.append(
            f'netsh advfirewall firewall add rule name="LateralX_BLOCK_{ip}" '
            f'dir=in action=block remoteip={ip}'
        )
        rules.append(f"ip access-list extended LATERALX_BLOCK\n  deny ip host {ip} any\n  deny ip any host {ip}")
        rules.append("")

    return rules


def generate_detection_rules_from_techniques_only(result: RCAResult) -> str:
    """
    Lightweight detection-rules HTML fragment for quick scan reports.
    Generates Sigma and YARA from stored IOCs and techniques — no event
    timeline required, so no Snort or behavioral rules are included.
    Uses the same CSS class names as report.py (_CSS) so it embeds cleanly.
    """
    sigma_rules = generate_sigma_rules(result.iocs, result.mitre_techniques)
    yara_rules  = generate_yara_rules(result.iocs, result.mitre_techniques)

    if not sigma_rules and not yara_rules:
        return ""

    note = (
        '<div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:6px;'
        'padding:10px 14px;margin-bottom:16px;font-size:12px;color:#0c4a6e">'
        'Quick scan — Sigma and YARA only. '
        'Run full analysis for network and firewall rules.</div>'
    )

    _sigma_fallback = '<p style="color:#64748b;font-size:12px">No Sigma rules generated.</p>'
    _yara_fallback  = '<p style="color:#64748b;font-size:12px">No YARA rules generated.</p>'

    sigma_entries = ""
    for r in sigma_rules[:12]:
        tags_str = ", ".join(r.get("tags", []))
        kw_str   = str(r["detection"].get("keywords", []))
        sigma_entries += (
            f'<div class="rule-entry">'
            f'<span style="color:#7dd3fc">title:</span> {r["title"]}\n'
            f'<span style="color:#7dd3fc">id:</span> {r["id"]}\n'
            f'<span style="color:#7dd3fc">tags:</span> {tags_str}\n'
            f'<span style="color:#86efac">detection:</span>\n'
            f'  keywords: {kw_str}'
            f'</div>'
        )

    yara_entries = "".join(
        f'<div class="rule-entry">{rule}</div>' for rule in yara_rules[:10]
    )

    sigma_col = (
        f'<div class="rule-block"><h4>Sigma Rules ({len(sigma_rules)} generated)</h4>'
        f'{sigma_entries or _sigma_fallback}'
        f'</div>'
    )
    yara_col = (
        f'<div class="rule-block"><h4>YARA Rules ({len(yara_rules)} generated)</h4>'
        f'{yara_entries or _yara_fallback}'
        f'</div>'
    )

    title = (
        f"Detection Rules — Sigma ({len(sigma_rules)}) · "
        f"YARA ({len(yara_rules)}) · Quick Scan"
    )
    body = note + f'<div class="rules-wrap">{sigma_col}{yara_col}</div>'
    return f'<div class="sec" data-ai-generated="false"><h2>{title}</h2>{body}</div>'


def rules_to_text(sigma_rules: list[dict], snort_rules: list[str], yara_rules: list[str] | None = None) -> str:
    """Produce a combined human-readable block for display or copy-paste."""
    lines: list[str] = []

    if sigma_rules:
        lines.append("# ── Sigma Rules ──────────────────────────────────────────────")
        for r in sigma_rules:
            lines.append(f"\ntitle: {r['title']}")
            lines.append(f"id: {r['id']}")
            lines.append(f"status: {r['status']}")
            lines.append(f"description: {r['description']}")
            lines.append("logsource:")
            for k, v in r["logsource"].items():
                lines.append(f"  {k}: {v}")
            lines.append("detection:")
            for kw in r["detection"]["keywords"]:
                lines.append(f"  keywords:\n    - {kw}")
            lines.append(f"  condition: {r['detection']['condition']}")
            lines.append(f"level: {r['level']}")
            lines.append(f"tags: {r['tags']}")
            lines.append("---")

    if yara_rules:
        lines.append("\n# ── YARA Rules ───────────────────────────────────────────────")
        lines.extend(yara_rules)

    if snort_rules:
        lines.append("\n# ── Snort / Suricata Rules ───────────────────────────────────")
        lines.extend(snort_rules)

    return "\n".join(lines)
