"""
Detection-as-Code — Sigma & Snort Rule Generator

Converts extracted MITRE techniques and IOCs into machine-readable detection
rules that the SOC team can import into SIEM/IDS platforms.

generate_behavioral_sigma_rules() additionally analyses the raw event timeline
and emits Sigma rules only when a behavioral sequence is actually present in
the data (evidence-gated). Patterns detected:
  1. Brute-force then success  (T1110)
  2. Encoded command execution (T1059.001)
  3. Lateral movement chain    (T1021)
  4. Recon then lateral move   (T1087 + T1021)
"""

import uuid
from collections import defaultdict
from datetime import timedelta
from backend.schema import ForensicEvent, IOC, MitreTechnique

# Starting SID for custom Snort rules (IANA private range 9000000+)
_SNORT_SID_BASE = 9_100_000

# Map MITRE tactic slugs to Sigma attack tag format
_TACTIC_TAG = {
    "Initial Access":        "initial_access",
    "Execution":             "execution",
    "Persistence":           "persistence",
    "Privilege Escalation":  "privilege_escalation",
    "Defense Evasion":       "defense_evasion",
    "Credential Access":     "credential_access",
    "Discovery":             "discovery",
    "Lateral Movement":      "lateral_movement",
    "Collection":            "collection",
    "Command and Control":   "command_and_control",
    "Exfiltration":          "exfiltration",
    "Impact":                "impact",
}


def generate_sigma_rules(
    iocs: list[IOC],
    techniques: list[MitreTechnique],
) -> list[dict]:
    """
    Return a list of Sigma rule dicts (one per unique MITRE technique).
    Each dict is directly YAML-serialisable.
    """
    rules: list[dict] = []
    seen_ids: set[str] = set()

    for tech in techniques:
        if tech.id in seen_ids:
            continue
        seen_ids.add(tech.id)

        tactic_slug = _TACTIC_TAG.get(tech.tactic, tech.tactic.lower().replace(" ", "_"))
        # Use UUID5 so the same technique always produces the same rule ID
        rule_id = str(uuid.uuid5(uuid.NAMESPACE_OID, f"fip-{tech.id}"))

        # Pull the evidence keyword from the technique or fall back to the technique name
        keyword = (tech.evidence or tech.name).split("|")[0].strip()[:80]

        rule: dict = {
            "title": f"FIP Detection — {tech.name}",
            "id": rule_id,
            "status": "experimental",
            "description": (
                f"Auto-generated by Forensic Intelligence Pipeline. "
                f"Technique {tech.id} ({tech.name}) detected in uploaded timeline."
            ),
            "references": [f"https://attack.mitre.org/techniques/{tech.id.replace('.', '/')}/"],
            "author": "FIP Auto-Generator",
            "logsource": {"product": "windows", "service": "security"},
            "detection": {
                "keywords": [keyword],
                "condition": "keywords",
            },
            "falsepositives": ["Legitimate administrative activity"],
            "level": "high",
            "tags": [
                f"attack.{tactic_slug}",
                f"attack.{tech.id.lower()}",
            ],
        }
        rules.append(rule)

    return rules


def generate_snort_rules(iocs: list[IOC]) -> list[str]:
    """
    Return a list of Snort/Suricata rule strings, one per unique IP IOC.
    SIDs start at 9_100_000 to avoid conflict with community rule sets.
    """
    rules: list[str] = []
    seen: set[str] = set()

    for idx, ioc in enumerate(iocs):
        if ioc.type != "ip" or ioc.value in seen:
            continue
        seen.add(ioc.value)
        sid = _SNORT_SID_BASE + idx
        # Sanitise context: remove quotes that would break the Snort msg field
        msg = ioc.context.replace('"', "'")[:120]
        rule = (
            f'alert ip any any -> {ioc.value} any '
            f'(msg:"FIP IOC — {msg}"; '
            f'sid:{sid}; rev:1;)'
        )
        rules.append(rule)

    return rules


_RECON_TOOLS = frozenset({
    "whoami", "net.exe", "net1.exe", "nltest", "tasklist", "ipconfig",
    "netstat", "arp", "nslookup", "ping", "systeminfo",
})

_LOGON_SUCCESS_IDS = frozenset({"4624", "4648", "4768", "4769"})
_LOGON_FAIL_ID = "4625"
_PROC_CREATE_ID = "4688"


def _sigma_rule(
    title: str,
    rule_key: str,
    description: str,
    keywords: list[str],
    condition: str,
    tags: list[str],
    level: str = "high",
) -> dict:
    rule_id = str(uuid.uuid5(uuid.NAMESPACE_OID, f"fip-behavioral-{rule_key}"))
    return {
        "title": title,
        "id": rule_id,
        "status": "experimental",
        "description": description,
        "references": [],
        "author": "FIP Behavioral Detector",
        "logsource": {"product": "windows", "service": "security"},
        "detection": {"keywords": keywords, "condition": condition},
        "falsepositives": ["Authorized penetration testing", "Help-desk password resets"],
        "level": level,
        "tags": tags,
    }


def generate_behavioral_sigma_rules(events: list[ForensicEvent]) -> list[dict]:
    """
    Scan the event timeline for behavioral attack sequences and return Sigma
    rules only for patterns that have evidence in the supplied events.
    """
    rules: list[dict] = []

    # Index events by user
    by_user: dict[str, list[ForensicEvent]] = defaultdict(list)
    for e in events:
        if e.user:
            by_user[e.user].append(e)
    for evs in by_user.values():
        evs.sort(key=lambda e: e.timestamp)

    # ── Pattern 1: Brute-force then success ───────────────────────────────────
    # ≥3 failed logins within 10 min, followed by success within 5 min after.
    _bf_window = timedelta(minutes=10)
    _bf_success_lag = timedelta(minutes=5)
    bf_users: list[str] = []

    for user, evs in by_user.items():
        failures = [e for e in evs if e.event_id == _LOGON_FAIL_ID]
        successes = [e for e in evs if e.event_id in _LOGON_SUCCESS_IDS]
        for i in range(len(failures)):
            window_end = failures[i].timestamp + _bf_window
            burst = [f for f in failures[i:] if f.timestamp <= window_end]
            if len(burst) >= 3:
                cutoff = burst[-1].timestamp + _bf_success_lag
                if any(s.timestamp >= failures[i].timestamp and s.timestamp <= cutoff
                       for s in successes):
                    bf_users.append(user)
                    break

    if bf_users:
        rules.append(_sigma_rule(
            title="FIP Behavioral — Brute-Force Authentication Followed by Success",
            rule_key="brute_force_success",
            description=(
                f"3+ consecutive failed logon attempts (EventID 4625) within 10 minutes "
                f"followed by a successful logon (EventID 4624/4648) within 5 minutes. "
                f"Evidence found for user(s): {', '.join(bf_users[:5])}."
            ),
            keywords=["EventID: 4625", "EventID: 4624", "EventID: 4648"],
            condition=(
                "selection_failure | count() by SubjectUserName > 3 within 10m | "
                "near selection_success within 5m"
            ),
            tags=["attack.credential_access", "attack.t1110"],
            level="high",
        ))

    # ── Pattern 2: Obfuscated / encoded command execution ─────────────────────
    _enc_markers = ("-enc", "encodedcommand", "base64")
    enc_events = [
        e for e in events
        if (e.event_id == _PROC_CREATE_ID or "process" in e.event_type.lower())
        and any(m in e.description.lower() for m in _enc_markers)
    ]

    if enc_events:
        hosts = list({e.source_host for e in enc_events})[:3]
        rules.append(_sigma_rule(
            title="FIP Behavioral — Encoded PowerShell / Obfuscated Command Execution",
            rule_key="encoded_command_exec",
            description=(
                f"Process creation event (EventID 4688) with -EncodedCommand, "
                f"encodedcommand, or base64 in the command line detected on: "
                f"{', '.join(hosts)}."
            ),
            keywords=["-EncodedCommand", "EncodedCommand", "base64"],
            condition="keywords",
            tags=["attack.execution", "attack.t1059.001", "attack.defense_evasion", "attack.t1027"],
            level="high",
        ))

    # ── Pattern 3: Lateral movement chain ────────────────────────────────────
    # A user authenticates to ≥3 distinct hosts within 30 min.
    _lat_window = timedelta(minutes=30)
    lat_users: list[str] = []

    for user, evs in by_user.items():
        logons = [e for e in evs if e.event_id in _LOGON_SUCCESS_IDS
                  or "logon" in e.event_type.lower()]
        for i in range(len(logons)):
            win_end = logons[i].timestamp + _lat_window
            hosts_in_window = {e.source_host for e in logons
                               if logons[i].timestamp <= e.timestamp <= win_end}
            if len(hosts_in_window) >= 3:
                lat_users.append(user)
                break

    if lat_users:
        rules.append(_sigma_rule(
            title="FIP Behavioral — Lateral Movement: Rapid Multi-Host Authentication",
            rule_key="lateral_movement_chain",
            description=(
                f"A single user authenticated to 3 or more distinct hosts within a "
                f"30-minute window, consistent with lateral movement. "
                f"Evidence found for user(s): {', '.join(lat_users[:5])}."
            ),
            keywords=["EventID: 4624", "EventID: 4648"],
            condition=(
                "selection | count(ComputerName) by SubjectUserName >= 3 within 30m"
            ),
            tags=["attack.lateral_movement", "attack.t1021"],
            level="high",
        ))

    # ── Pattern 4: Recon tools followed by lateral move ──────────────────────
    _recon_lag = timedelta(minutes=15)
    recon_pivot_users: list[str] = []

    for user, evs in by_user.items():
        recon_evs = [
            e for e in evs
            if any(t in e.description.lower() for t in _RECON_TOOLS)
        ]
        logon_evs = [e for e in evs if e.event_id in _LOGON_SUCCESS_IDS]
        for recon in recon_evs:
            cutoff = recon.timestamp + _recon_lag
            pivot = [
                l for l in logon_evs
                if l.timestamp > recon.timestamp
                and l.timestamp <= cutoff
                and l.source_host != recon.source_host
            ]
            if pivot:
                recon_pivot_users.append(user)
                break

    if recon_pivot_users:
        rules.append(_sigma_rule(
            title="FIP Behavioral — Reconnaissance Followed by Lateral Movement",
            rule_key="recon_then_pivot",
            description=(
                f"Discovery/recon tool usage (whoami, net.exe, nltest, etc.) followed "
                f"within 15 minutes by a successful logon to a different host. "
                f"Evidence found for user(s): {', '.join(recon_pivot_users[:5])}."
            ),
            keywords=list(_RECON_TOOLS)[:6] + ["EventID: 4624"],
            condition=(
                "selection_recon | near selection_logon within 15m"
            ),
            tags=["attack.discovery", "attack.t1087", "attack.lateral_movement", "attack.t1021"],
            level="medium",
        ))

    return rules


def rules_to_text(sigma_rules: list[dict], snort_rules: list[str]) -> str:
    """Produce a combined human-readable block for display or copy-paste."""
    lines: list[str] = []

    if sigma_rules:
        lines.append("# ── Sigma Rules ──────────────────────────────────────────────")
        for r in sigma_rules:
            lines.append(f"\ntitle: {r['title']}")
            lines.append(f"id: {r['id']}")
            lines.append(f"status: {r['status']}")
            lines.append(f"description: {r['description']}")
            lines.append("logsource:")
            lines.append(f"  product: {r['logsource']['product']}")
            lines.append(f"  service: {r['logsource']['service']}")
            lines.append("detection:")
            for kw in r["detection"]["keywords"]:
                lines.append(f"  keywords:\n    - {kw}")
            lines.append(f"  condition: {r['detection']['condition']}")
            lines.append(f"level: {r['level']}")
            lines.append(f"tags: {r['tags']}")
            lines.append("---")

    if snort_rules:
        lines.append("\n# ── Snort / Suricata Rules ───────────────────────────────────")
        lines.extend(snort_rules)

    return "\n".join(lines)
